language: python
  python:
    - "3.6"
  env:
    - DJANGO=1.11
  install:
    - pip install -r requirements.txt
  script:
    - python manage.py test
  before_install:
    - sudo apt-get update
    - sudo apt-get install -y 
